#############################################################################
# Makefile for building: BackgroundVideo
# Generated by qmake (2.01a) (Qt 4.7.4) on: Mon 15. Jun 22:55:24 2015
# Project:  BackgroundVideo.pro
# Template: app
# Command: c:\qtsdk\symbian\sdks\symbiansr1qt474\bin\qmake.exe -spec ..\..\..\QtSDK\Symbian\SDKs\SymbianSR1Qt474\mkspecs\symbian-sbsv2 CONFIG+=release -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o bld.inf BackgroundVideo.pro
#############################################################################

MAKEFILE          = Makefile
QMAKE             = c:\qtsdk\symbian\sdks\symbiansr1qt474\bin\qmake.exe
DEL_FILE          = del /q 2> NUL
DEL_DIR           = rmdir
CHK_DIR_EXISTS    = if not exist
MKDIR             = mkdir
MOVE              = move
DEBUG_PLATFORMS   = winscw gcce armv5 armv6
RELEASE_PLATFORMS = gcce armv5 armv6
MAKE              = make
SBS               = sbs

DEFINES	 = -DSYMBIAN -DUNICODE -DQT_KEYPAD_NAVIGATION -DQT_SOFTKEYS_ENABLED -DQT_USE_MATH_H_FLOATS -DDOCUMENT_GALLERY -DQ_COMPONENTS_SYMBIAN -DHAVE_MOBILITY -DQT_NO_DEBUG -DQT_DECLARATIVE_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
INCPATH	 =  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/include/QtCore"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/include/QtNetwork"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/include/QtGui"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/include/QtOpenGL"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/include/QtDeclarative"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/include"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/mkspecs/common/symbian"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/stdapis"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/stdapis/sys"  -I"C:/Users/me/BackgroundVideo/qmlapplicationviewer"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/mw"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform/mw"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform/loc"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform/mw/loc"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform/loc/sc"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform/mw/loc/sc"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/stdapis/stlportv5"  -I"C:/Users/me/BackgroundVideo/moc"  -I"C:/Users/me/BackgroundVideo"  -I"C:/Users/me/BackgroundVideo/rcc"  -I"C:/Users/me/BackgroundVideo/ui" 
first: default

all: debug release

default: debug-winscw
qmake:
	$(QMAKE) "C:/Users/me/BackgroundVideo/BackgroundVideo.pro"  -spec ..\..\..\QtSDK\Symbian\SDKs\SymbianSR1Qt474\mkspecs\symbian-sbsv2 CONFIG+=release -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

bld.inf: C:/Users/me/BackgroundVideo/BackgroundVideo.pro
	$(QMAKE) "C:/Users/me/BackgroundVideo/BackgroundVideo.pro"  -spec ..\..\..\QtSDK\Symbian\SDKs\SymbianSR1Qt474\mkspecs\symbian-sbsv2 CONFIG+=release -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

c:\Users\me\BackgroundVideo\BackgroundVideo.loc: 
	$(QMAKE) "C:/Users/me/BackgroundVideo/BackgroundVideo.pro"  -spec ..\..\..\QtSDK\Symbian\SDKs\SymbianSR1Qt474\mkspecs\symbian-sbsv2 CONFIG+=release -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

debug: c:\Users\me\BackgroundVideo\BackgroundVideo.loc bld.inf
	$(SBS) -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1
clean-debug: bld.inf
	$(SBS) reallyclean --toolcheck=off -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1
freeze-debug: bld.inf
	$(SBS) freeze -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1
release: c:\Users\me\BackgroundVideo\BackgroundVideo.loc bld.inf
	$(SBS) -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1
clean-release: bld.inf
	$(SBS) reallyclean --toolcheck=off -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1
freeze-release: bld.inf
	$(SBS) freeze -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1

debug-winscw: c:\Users\me\BackgroundVideo\BackgroundVideo.loc bld.inf
	$(SBS) -c winscw_udeb.mwccinc
clean-debug-winscw: bld.inf
	$(SBS) reallyclean -c winscw_udeb.mwccinc
freeze-debug-winscw: bld.inf
	$(SBS) freeze -c winscw_udeb.mwccinc
debug-gcce: c:\Users\me\BackgroundVideo\BackgroundVideo.loc bld.inf
	$(SBS) -c arm.v5.udeb.gcce4_4_1
clean-debug-gcce: bld.inf
	$(SBS) reallyclean -c arm.v5.udeb.gcce4_4_1
freeze-debug-gcce: bld.inf
	$(SBS) freeze -c arm.v5.udeb.gcce4_4_1
debug-armv5: c:\Users\me\BackgroundVideo\BackgroundVideo.loc bld.inf
	$(SBS) -c armv5_udeb
clean-debug-armv5: bld.inf
	$(SBS) reallyclean -c armv5_udeb
freeze-debug-armv5: bld.inf
	$(SBS) freeze -c armv5_udeb
debug-armv6: c:\Users\me\BackgroundVideo\BackgroundVideo.loc bld.inf
	$(SBS) -c armv6_udeb
clean-debug-armv6: bld.inf
	$(SBS) reallyclean -c armv6_udeb
freeze-debug-armv6: bld.inf
	$(SBS) freeze -c armv6_udeb
release-gcce: c:\Users\me\BackgroundVideo\BackgroundVideo.loc bld.inf
	$(SBS) -c arm.v5.urel.gcce4_4_1
clean-release-gcce: bld.inf
	$(SBS) reallyclean -c arm.v5.urel.gcce4_4_1
freeze-release-gcce: bld.inf
	$(SBS) freeze -c arm.v5.urel.gcce4_4_1
release-armv5: c:\Users\me\BackgroundVideo\BackgroundVideo.loc bld.inf
	$(SBS) -c armv5_urel
clean-release-armv5: bld.inf
	$(SBS) reallyclean -c armv5_urel
freeze-release-armv5: bld.inf
	$(SBS) freeze -c armv5_urel
release-armv6: c:\Users\me\BackgroundVideo\BackgroundVideo.loc bld.inf
	$(SBS) -c armv6_urel
clean-release-armv6: bld.inf
	$(SBS) reallyclean -c armv6_urel
freeze-release-armv6: bld.inf
	$(SBS) freeze -c armv6_urel
debug-armv5-gcce4.4.1: c:\Users\me\BackgroundVideo\BackgroundVideo.loc bld.inf
	$(SBS) -c arm.v5.udeb.gcce4_4_1
clean-debug-armv5-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v5.udeb.gcce4_4_1
freeze-debug-armv5-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v5.udeb.gcce4_4_1
release-armv5-gcce4.4.1: c:\Users\me\BackgroundVideo\BackgroundVideo.loc bld.inf
	$(SBS) -c arm.v5.urel.gcce4_4_1
clean-release-armv5-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v5.urel.gcce4_4_1
freeze-release-armv5-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v5.urel.gcce4_4_1
debug-armv6-gcce4.4.1: c:\Users\me\BackgroundVideo\BackgroundVideo.loc bld.inf
	$(SBS) -c arm.v6.udeb.gcce4_4_1
clean-debug-armv6-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v6.udeb.gcce4_4_1
freeze-debug-armv6-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v6.udeb.gcce4_4_1
release-armv6-gcce4.4.1: c:\Users\me\BackgroundVideo\BackgroundVideo.loc bld.inf
	$(SBS) -c arm.v6.urel.gcce4_4_1
clean-release-armv6-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v6.urel.gcce4_4_1
freeze-release-armv6-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v6.urel.gcce4_4_1

export: bld.inf
	$(SBS) export -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1 -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1

cleanexport: bld.inf
	$(SBS) cleanexport -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1 -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1

freeze: freeze-release

check: first

run:
	call C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/release/winscw/udeb/BackgroundVideo.exe $(QT_RUN_OPTIONS)

runonphone: sis
	runonphone $(QT_RUN_ON_PHONE_OPTIONS) --sis BackgroundVideo.sis BackgroundVideo.exe $(QT_RUN_OPTIONS)

BackgroundVideo_template.pkg: C:/Users/me/BackgroundVideo/BackgroundVideo.pro
	$(MAKE) -f $(MAKEFILE) qmake

BackgroundVideo_installer.pkg: C:/Users/me/BackgroundVideo/BackgroundVideo.pro
	$(MAKE) -f $(MAKEFILE) qmake

BackgroundVideo_stub.pkg: C:/Users/me/BackgroundVideo/BackgroundVideo.pro
	$(MAKE) -f $(MAKEFILE) qmake

sis: BackgroundVideo_template.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_sis:
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\createpackage.bat -g $(QT_SIS_OPTIONS) BackgroundVideo_template.pkg $(QT_SIS_TARGET) $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

unsigned_sis: BackgroundVideo_template.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_unsigned_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_unsigned_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_unsigned_sis:
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\createpackage.bat -g $(QT_SIS_OPTIONS) -o BackgroundVideo_template.pkg $(QT_SIS_TARGET)

BackgroundVideo.sis:
	$(MAKE) -f $(MAKEFILE) sis

installer_sis: BackgroundVideo_installer.pkg sis
	$(MAKE) -f $(MAKEFILE) ok_installer_sis

ok_installer_sis: BackgroundVideo_installer.pkg
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\createpackage.bat $(QT_SIS_OPTIONS) BackgroundVideo_installer.pkg - $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

unsigned_installer_sis: BackgroundVideo_installer.pkg unsigned_sis
	$(MAKE) -f $(MAKEFILE) ok_unsigned_installer_sis

ok_unsigned_installer_sis: BackgroundVideo_installer.pkg
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\createpackage.bat $(QT_SIS_OPTIONS) -o BackgroundVideo_installer.pkg

fail_sis_nocache:
	$(error Project has to be built or QT_SIS_TARGET environment variable has to be set before calling 'SIS' target)

stub_sis: BackgroundVideo_stub.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_stub_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_stub_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_stub_sis:
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\createpackage.bat -s $(QT_SIS_OPTIONS) BackgroundVideo_stub.pkg $(QT_SIS_TARGET) $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

deploy: sis
	call BackgroundVideo.sis

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc\moc_qmlapplicationviewer.cpp moc\moc_qmlutils.cpp moc\moc_mediakeysobserver.cpp moc\moc_qsymbianapplication.cpp moc\moc_settings.cpp moc\moc_downloadmanager.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc\moc_qmlapplicationviewer.cpp moc\moc_qmlutils.cpp moc\moc_mediakeysobserver.cpp moc\moc_qsymbianapplication.cpp moc\moc_settings.cpp moc\moc_downloadmanager.cpp
moc\moc_qmlapplicationviewer.cpp: qmlapplicationviewer\qmlapplicationviewer.h
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\me\BackgroundVideo\qmlapplicationviewer\qmlapplicationviewer.h -o c:\Users\me\BackgroundVideo\moc\moc_qmlapplicationviewer.cpp

moc\moc_qmlutils.cpp: qmlutils.h
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\me\BackgroundVideo\qmlutils.h -o c:\Users\me\BackgroundVideo\moc\moc_qmlutils.cpp

moc\moc_mediakeysobserver.cpp: mediakeysobserver.h
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\me\BackgroundVideo\mediakeysobserver.h -o c:\Users\me\BackgroundVideo\moc\moc_mediakeysobserver.cpp

moc\moc_qsymbianapplication.cpp: qsymbianapplication.h
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\me\BackgroundVideo\qsymbianapplication.h -o c:\Users\me\BackgroundVideo\moc\moc_qsymbianapplication.cpp

moc\moc_settings.cpp: settings.h
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\me\BackgroundVideo\settings.h -o c:\Users\me\BackgroundVideo\moc\moc_settings.cpp

moc\moc_downloadmanager.cpp: downloadmanager.h
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\me\BackgroundVideo\downloadmanager.h -o c:\Users\me\BackgroundVideo\moc\moc_downloadmanager.cpp

compiler_rcc_make_all: rcc\qrc_res.cpp
compiler_rcc_clean:
	-$(DEL_FILE) rcc\qrc_res.cpp
rcc\qrc_res.cpp: res.qrc \
		qml\BackgroundVideo\PlaylistPage.qml \
		qml\BackgroundVideo\RectUtils.js \
		qml\BackgroundVideo\Settings.js \
		qml\BackgroundVideo\ProgressBarMod.qml \
		qml\BackgroundVideo\Controls.qml \
		qml\BackgroundVideo\ProfileChangeDialog.qml \
		qml\BackgroundVideo\AddFavouriteDialog.qml \
		qml\BackgroundVideo\Settings.qml \
		qml\BackgroundVideo\Favourites.qml \
		qml\BackgroundVideo\FilePickerPage.qml \
		qml\BackgroundVideo\Popuper.qml \
		qml\BackgroundVideo\LoaderMenu.qml \
		qml\BackgroundVideo\TileVideoLoader.qml \
		qml\BackgroundVideo\TileVideoLoaderBackground.qml \
		qml\BackgroundVideo\ContextMenuer.qml \
		qml\BackgroundVideo\ResetDialog.qml \
		qml\BackgroundVideo\DownloadManagerProgress.qml \
		qml\BackgroundVideo\VolumeChanger.qml \
		qml\BackgroundVideo\StartUI.qml \
		qml\BackgroundVideo\FavLongMenu.qml \
		qml\BackgroundVideo\MenuButton.qml \
		qml\BackgroundVideo\StreamingDialog.qml \
		qml\BackgroundVideo\Bar.qml \
		qml\BackgroundVideo\Playlist.qml \
		qml\BackgroundVideo\Bookmarks.js \
		qml\BackgroundVideo\MenuContenter.qml \
		qml\BackgroundVideo\StartUIItem.qml \
		qml\BackgroundVideo\BackgroundPlayerUI.qml \
		qml\BackgroundVideo\main.qml \
		qml\BackgroundVideo\PlaylistPlayer.qml \
		qml\BackgroundVideo\Fader.qml \
		qml\BackgroundVideo\AppPage.qml \
		qml\BackgroundVideo\DownloadDialog.qml \
		qml\BackgroundVideo\PlayMenu.qml \
		qml\BackgroundVideo\Infomation.qml \
		qml\BackgroundVideo\AppManager.js \
		qml\BackgroundVideo\img\fast_forward.svg \
		qml\BackgroundVideo\img\favourite.svg \
		qml\BackgroundVideo\img\settings.svg \
		qml\BackgroundVideo\img\volume.svg \
		qml\BackgroundVideo\img\volume_increase.svg \
		qml\BackgroundVideo\img\mute.svg \
		qml\BackgroundVideo\img\noVideo.svg \
		qml\BackgroundVideo\img\home.svg \
		qml\BackgroundVideo\img\information_userguide.svg \
		qml\BackgroundVideo\img\volume_decrease.svg \
		qml\BackgroundVideo\img\rewind.svg \
		qml\BackgroundVideo\img\download.svg \
		qml\BackgroundVideo\img\button_option_enabled.svg \
		qml\BackgroundVideo\img\next.svg \
		qml\BackgroundVideo\img\qtg_fr_progressbar_fill_red.svg \
		qml\BackgroundVideo\img\filmstrip.svg \
		qml\BackgroundVideo\img\qtg_fr_progressbar_fill.svg \
		qml\BackgroundVideo\img\close.svg \
		qml\BackgroundVideo\img\qtg_fr_popup_black.svg \
		qml\BackgroundVideo\img\shuffle.svg \
		qml\BackgroundVideo\img\button_option_enabled_dark.svg \
		qml\BackgroundVideo\img\video.svg \
		qml\BackgroundVideo\img\pause.svg \
		qml\BackgroundVideo\img\back1.svg \
		qml\BackgroundVideo\img\minimize.svg \
		qml\BackgroundVideo\img\stop.svg \
		qml\BackgroundVideo\img\play.svg \
		qml\BackgroundVideo\img\ok.svg \
		qml\BackgroundVideo\img\repeat.svg \
		qml\BackgroundVideo\img\back.png
	c:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\rcc.exe -name res c:\Users\me\BackgroundVideo\res.qrc -o c:\Users\me\BackgroundVideo\rcc\qrc_res.cpp

compiler_image_collection_make_all: ui\qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) ui\qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

dodistclean:
	-@ if EXIST "c:\Users\me\BackgroundVideo\BackgroundVideo_template.pkg" $(DEL_FILE)  "c:\Users\me\BackgroundVideo\BackgroundVideo_template.pkg"
	-@ if EXIST "c:\Users\me\BackgroundVideo\BackgroundVideo_stub.pkg" $(DEL_FILE)  "c:\Users\me\BackgroundVideo\BackgroundVideo_stub.pkg"
	-@ if EXIST "c:\Users\me\BackgroundVideo\BackgroundVideo_installer.pkg" $(DEL_FILE)  "c:\Users\me\BackgroundVideo\BackgroundVideo_installer.pkg"
	-@ if EXIST "c:\Users\me\BackgroundVideo\Makefile" $(DEL_FILE)  "c:\Users\me\BackgroundVideo\Makefile"
	-@ if EXIST "c:\Users\me\BackgroundVideo\BackgroundVideo_exe.mmp" $(DEL_FILE)  "c:\Users\me\BackgroundVideo\BackgroundVideo_exe.mmp"
	-@ if EXIST "c:\Users\me\BackgroundVideo\BackgroundVideo_reg.rss" $(DEL_FILE)  "c:\Users\me\BackgroundVideo\BackgroundVideo_reg.rss"
	-@ if EXIST "c:\Users\me\BackgroundVideo\BackgroundVideo.rss" $(DEL_FILE)  "c:\Users\me\BackgroundVideo\BackgroundVideo.rss"
	-@ if EXIST "c:\Users\me\BackgroundVideo\BackgroundVideo.loc" $(DEL_FILE)  "c:\Users\me\BackgroundVideo\BackgroundVideo.loc"
	-@ if EXIST "c:\Users\me\BackgroundVideo\bld.inf" $(DEL_FILE)  "c:\Users\me\BackgroundVideo\bld.inf"

distclean: clean dodistclean

clean: bld.inf
	-$(SBS) reallyclean --toolcheck=off -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1 -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1


